spring:
  kafka:
    streams:
      bootstrap-servers: "localhost:9092"
      application-id: "cobranca-application"
  mail:
    host: "smtp.gmail.com"
    port: "587"
    username: "bancobacana123@gmail.com"
    password: "drxd eohp ozco gtkf"
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"