spring:
  kafka:
    streams:
      bootstrap-servers: "localhost:9092"
      application-id: "cobranca-application"
  mail:
    host: "smtp.gmail.com"
    port: "587"
    username: "vin.felipes@gmail.com"
    password: "nfax nudu rimo hstd"
    properties:
      mail:
        smtp:
          auth: "true"
          starttls:
            enable: "true"